### ISSUE TITLE
[REQUEST] More information about DRAW tap 

### ISSUE THREAD

**Issue by limulu-k** [Kang-Minseokk/Invaders-SDP#7]
## Problem Description
![image-20241110231032366](https://github.com/user-attachments/assets/5bd1f3bc-884a-465f-b710-fa5728ce15e3)
There is no explanation on how to use the custom tab and how many coins are need. Also, I don't know if it's working when I press the space bar on the draw tab, or if it's picked, or which skin was picked. It would be nice if you could add an effect sound.

custom 탭을 어떻게 사용하며 사용되는 재화는 몇인지에 대한 설명이 없습니다. 또한 draw 탭에서 스페이스바로 눌렀을 때 진행이 되는건지, 뽑힌건지 어떤 skin이 뽑힌건지 모르겠습니다. Effect sound 도 추가해주면 좋을거 같습니다.

**Comment by seongmin0244** [comment]
logger info로 나타내긴 했는데 참고하겠습니다!

**Comment by limulu-k** [comment]
> logger info로 나타내긴 했는데 참고하겠습니다!

사용자는 로그화면을 못봅니다. 로그는 개발자가 프로그램이 어떻게 동작했는지 확인하려고 남기는거라 로그내용을 사용자가 봐서는 안됩니다.

**Comment by seongmin0244** [comment]
아,,  네 알겠습니다 ㅎㅎ
