### ISSUE TITLE
[REQUEST] Add necessary coin growth mechanism

### ISSUE THREAD

**Issue by limulu-k** [Kang-Minseokk/Invaders-SDP#8]
## Problem Description
![image-20241110232346024](https://github.com/user-attachments/assets/5eee5ce7-1681-40c6-8318-7063a63b4155)
The needed consumed coin is literally set to 1. It seems that this value was not modified during testing, so it may need to be adjusted.

Currently, the success rate is 100%, so a mechanism where, for example, unlocking 1 item costs 50 coins, unlocking 2 items costs 100 coins, and so on, may be necessary.

말 그대로 소모 재화가 1입니다. 해당 사항 테스트 과정에서 변경하지 않은거 같은데 해당 값 변경이 필요할거 같습니다.
현재 확률이 100% 이기 때문에 예를 들면 1개가 해금 됐으면 50원, 2개가 해금 됐으면 100원,,,, 과 같은 메커니즘 추가가 필요해 보입니다.

**Comment by seongmin0244** [comment]
일단 리뷰하시기 편하시라고 1원으로 두었습니다..!
추가했습니당
